apiVersion: apps/v1
kind: Deployment
metadata:
  name: insightink-server-deployment
  labels:
    app: insightink-server
  annotations:
    commit_sha: "{{COMMIT_SHA}}"
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: insightink-server
  template:
    metadata:
      labels:
        app: insightink-server
    spec:
      imagePullSecrets:
        - name: acr-auth # Reference to the secret created
      containers:
        - name: insightink-server-container
          image: appacr.azurecr.io/insightink-server:{{COMMIT_SHA}} # Docker image
          ports:
            - containerPort: 3000 # Port that your Node.js app is running on
          env:
            - name: NODE_ENV
              value: "production" # Set Node.js environment to production
            - name: DATABASE_URI
              value: "mongodb://cosmosdb-account-58075:SP4nnZSNDyEAPzaQ98B2LxrXDV9fsQJ3VEJ8wMjl6DyWLVIejVDaX35kAtiddqTOwAyxKrSJDsj5ACDbeM5znw==@cosmosdb-account-58075.mongo.cosmos.azure.com:10255/insightink_db?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@cosmosdb-account-58075@" # Example environment variable for database connection
            - name: JWT_SECRET
              value: DEV_SECRET
            - name: MAIL_CONNECTION_STRING
              value: endpoint=https://app-com-service.india.communication.azure.com/;accesskey=DdHsGRc04R0NX5ufbOYnSgd2AxkbyMKgKLnFqFv9dDknMz1xdCI2JQQJ99AJACULyCpZVC32AAAAAZCSWRRD
            - name: CLIENT_DOMAIN
              value: https://happy-bay-041cccf00-preview.eastasia.5.azurestaticapps.net
            - name: CLOUDINARY_NAME
              value: test
            - name: CLOUDINARY_API_KEY
              value: test
            - name: CLOUDINARY_API_SECRET
              value: test
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: insightink-server-service
spec:
  selector:
    app: insightink-server
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 3000 # Port exposed by the container (from the containerPort)
  type: LoadBalancer # Expose the service via a load balancer (use NodePort for internal access)
